---
version: '2.3'
services:
  postgres:
    container_name: postgresdb
    hostname: postgresdb
    image: postgres:14.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin4
    hostname: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"

  redis-cluster:
    image: duyquyen/redis-cluster:latest
    container_name: redis-cluster
    ports:
      - "6379-6384:6379-6384"
    environment:
      IP: 0.0.0.0
      INITIAL_PORT: 6379